version: "3"
services:
  pubsub:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    ports:
      - 8000:80

  sfu:
    image: pionwebrtc/ion-sfu:latest-allrpc
    command: -c /configs/sfu.toml -jaddr :7000 -gaddr :50051
    ports:
      - "5000-5200:5000-5200/udp"
      - 7000:7000
