// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/sfu.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishRequest struct {
	Rid                  string              `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Options              *Options            `protobuf:"bytes,3,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{0}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

func (m *PublishRequest) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *PublishRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type PublishReply struct {
	Mid                  string              `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *PublishReply) Reset()         { *m = PublishReply{} }
func (m *PublishReply) String() string { return proto.CompactTextString(m) }
func (*PublishReply) ProtoMessage()    {}
func (*PublishReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{1}
}

func (m *PublishReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReply.Unmarshal(m, b)
}
func (m *PublishReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReply.Marshal(b, m, deterministic)
}
func (m *PublishReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReply.Merge(m, src)
}
func (m *PublishReply) XXX_Size() int {
	return xxx_messageInfo_PublishReply.Size(m)
}
func (m *PublishReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReply proto.InternalMessageInfo

func (m *PublishReply) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *PublishReply) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type UnpublishRequest struct {
	Mid                  string   `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnpublishRequest) Reset()         { *m = UnpublishRequest{} }
func (m *UnpublishRequest) String() string { return proto.CompactTextString(m) }
func (*UnpublishRequest) ProtoMessage()    {}
func (*UnpublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{2}
}

func (m *UnpublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnpublishRequest.Unmarshal(m, b)
}
func (m *UnpublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnpublishRequest.Marshal(b, m, deterministic)
}
func (m *UnpublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnpublishRequest.Merge(m, src)
}
func (m *UnpublishRequest) XXX_Size() int {
	return xxx_messageInfo_UnpublishRequest.Size(m)
}
func (m *UnpublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnpublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnpublishRequest proto.InternalMessageInfo

func (m *UnpublishRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type UnpublishReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnpublishReply) Reset()         { *m = UnpublishReply{} }
func (m *UnpublishReply) String() string { return proto.CompactTextString(m) }
func (*UnpublishReply) ProtoMessage()    {}
func (*UnpublishReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{3}
}

func (m *UnpublishReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnpublishReply.Unmarshal(m, b)
}
func (m *UnpublishReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnpublishReply.Marshal(b, m, deterministic)
}
func (m *UnpublishReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnpublishReply.Merge(m, src)
}
func (m *UnpublishReply) XXX_Size() int {
	return xxx_messageInfo_UnpublishReply.Size(m)
}
func (m *UnpublishReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnpublishReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnpublishReply proto.InternalMessageInfo

type SubscribeRequest struct {
	Mid                  string              `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Options              *Options            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{4}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *SubscribeRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SubscribeRequest) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type SubscribeReply struct {
	Mid                  string              `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubscribeReply) Reset()         { *m = SubscribeReply{} }
func (m *SubscribeReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeReply) ProtoMessage()    {}
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{5}
}

func (m *SubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReply.Unmarshal(m, b)
}
func (m *SubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReply.Marshal(b, m, deterministic)
}
func (m *SubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReply.Merge(m, src)
}
func (m *SubscribeReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeReply.Size(m)
}
func (m *SubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReply proto.InternalMessageInfo

func (m *SubscribeReply) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *SubscribeReply) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type UnsubscribeRequest struct {
	Mid                  string   `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{6}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type UnsubscribeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeReply) Reset()         { *m = UnsubscribeReply{} }
func (m *UnsubscribeReply) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeReply) ProtoMessage()    {}
func (*UnsubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{7}
}

func (m *UnsubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeReply.Unmarshal(m, b)
}
func (m *UnsubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeReply.Marshal(b, m, deterministic)
}
func (m *UnsubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeReply.Merge(m, src)
}
func (m *UnsubscribeReply) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeReply.Size(m)
}
func (m *UnsubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeReply proto.InternalMessageInfo

type SessionDescription struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sdp                  string   `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionDescription) Reset()         { *m = SessionDescription{} }
func (m *SessionDescription) String() string { return proto.CompactTextString(m) }
func (*SessionDescription) ProtoMessage()    {}
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{8}
}

func (m *SessionDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionDescription.Unmarshal(m, b)
}
func (m *SessionDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionDescription.Marshal(b, m, deterministic)
}
func (m *SessionDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionDescription.Merge(m, src)
}
func (m *SessionDescription) XXX_Size() int {
	return xxx_messageInfo_SessionDescription.Size(m)
}
func (m *SessionDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionDescription.DiscardUnknown(m)
}

var xxx_messageInfo_SessionDescription proto.InternalMessageInfo

func (m *SessionDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionDescription) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type Options struct {
	Bandwidth            uint32   `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Transportcc          bool     `protobuf:"varint,2,opt,name=transportcc,proto3" json:"transportcc,omitempty"`
	Codec                string   `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{9}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetBandwidth() uint32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *Options) GetTransportcc() bool {
	if m != nil {
		return m.Transportcc
	}
	return false
}

func (m *Options) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "sfu.PublishRequest")
	proto.RegisterType((*PublishReply)(nil), "sfu.PublishReply")
	proto.RegisterType((*UnpublishRequest)(nil), "sfu.UnpublishRequest")
	proto.RegisterType((*UnpublishReply)(nil), "sfu.UnpublishReply")
	proto.RegisterType((*SubscribeRequest)(nil), "sfu.SubscribeRequest")
	proto.RegisterType((*SubscribeReply)(nil), "sfu.SubscribeReply")
	proto.RegisterType((*UnsubscribeRequest)(nil), "sfu.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeReply)(nil), "sfu.UnsubscribeReply")
	proto.RegisterType((*SessionDescription)(nil), "sfu.SessionDescription")
	proto.RegisterType((*Options)(nil), "sfu.Options")
}

func init() { proto.RegisterFile("pkg/proto/sfu.proto", fileDescriptor_e599a6ad2e115568) }

var fileDescriptor_e599a6ad2e115568 = []byte{
	// 420 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x5d, 0x0f, 0xd2, 0x30,
	0x14, 0x65, 0x4c, 0xc5, 0xdd, 0x21, 0x99, 0x17, 0x09, 0x84, 0xf8, 0x80, 0xd5, 0x10, 0x5e, 0x64,
	0x06, 0xe3, 0x03, 0xbe, 0x98, 0x18, 0xe3, 0xab, 0xa6, 0x84, 0x17, 0x8d, 0x31, 0xec, 0x03, 0x68,
	0x84, 0xb6, 0xae, 0x5d, 0x0c, 0x3f, 0xc0, 0xf8, 0x83, 0xfd, 0x03, 0xa6, 0x65, 0x8e, 0x6d, 0x44,
	0x8d, 0xd1, 0x27, 0x2e, 0xb7, 0x3d, 0xa7, 0xe7, 0x9c, 0x7b, 0x33, 0xe8, 0xcb, 0x4f, 0xbb, 0x50,
	0x66, 0x42, 0x8b, 0x50, 0x6d, 0xf3, 0xb9, 0xad, 0xd0, 0x55, 0xdb, 0x9c, 0x7c, 0x75, 0xa0, 0xf7,
	0x36, 0x8f, 0x0e, 0x4c, 0xed, 0x69, 0xfa, 0x39, 0x4f, 0x95, 0xc6, 0x00, 0xdc, 0x8c, 0x25, 0x23,
	0x67, 0xe2, 0xcc, 0x3c, 0x6a, 0x4a, 0x5c, 0x82, 0x9f, 0xa4, 0x2a, 0xce, 0x98, 0xd4, 0x4c, 0xf0,
	0x51, 0x7b, 0xe2, 0xcc, 0xfc, 0xc5, 0x70, 0x6e, 0xa8, 0x56, 0xa9, 0x52, 0x4c, 0xf0, 0x57, 0x97,
	0x63, 0x5a, 0xbd, 0x8b, 0x53, 0xe8, 0x08, 0x5b, 0xa9, 0x91, 0x6b, 0x61, 0x5d, 0x0b, 0x7b, 0x73,
	0xee, 0xd1, 0x9f, 0x87, 0xe4, 0x3d, 0x74, 0x4b, 0x19, 0xf2, 0x70, 0x32, 0x22, 0x8e, 0x17, 0x11,
	0xc7, 0x7f, 0x12, 0x41, 0x1e, 0x41, 0xb0, 0xe6, 0xf2, 0xca, 0x65, 0xfd, 0x01, 0x12, 0x40, 0xaf,
	0x72, 0x4b, 0x1e, 0x4e, 0xe4, 0x9b, 0x03, 0xc1, 0x2a, 0x8f, 0x0c, 0x51, 0x94, 0xfe, 0x12, 0x58,
	0xf5, 0xd8, 0xfe, 0x8d, 0xc7, 0xa6, 0x03, 0xf7, 0x2f, 0x1c, 0x7c, 0x80, 0x5e, 0x45, 0xc8, 0x7f,
	0x0f, 0x68, 0x0a, 0xb8, 0xe6, 0xea, 0x8f, 0x4e, 0x09, 0x9a, 0x20, 0x55, 0x4d, 0x08, 0x79, 0x0e,
	0x78, 0x4d, 0x8f, 0x08, 0x37, 0xf4, 0x49, 0xa6, 0x05, 0xd8, 0xd6, 0x86, 0x4f, 0x25, 0xd2, 0x0a,
	0xf3, 0xa8, 0x29, 0xc9, 0x47, 0xe8, 0x14, 0x29, 0xe1, 0x7d, 0xf0, 0xa2, 0x0d, 0x4f, 0xbe, 0xb0,
	0x44, 0xef, 0x2d, 0xea, 0x0e, 0xbd, 0x34, 0x70, 0x02, 0xbe, 0xce, 0x36, 0x5c, 0x49, 0x91, 0xe9,
	0x38, 0xb6, 0x14, 0xb7, 0x69, 0xb5, 0x85, 0xf7, 0xe0, 0x66, 0x2c, 0x92, 0x34, 0xb6, 0xb1, 0x7a,
	0xf4, 0xfc, 0x67, 0xf1, 0xdd, 0x01, 0x77, 0xf5, 0x7a, 0x8d, 0xcf, 0xa0, 0x53, 0xac, 0x17, 0xf6,
	0x6d, 0x22, 0xf5, 0x9d, 0x1f, 0xdf, 0xad, 0x37, 0x8d, 0xaf, 0xd6, 0x13, 0x07, 0x97, 0xe0, 0x95,
	0x2b, 0x81, 0x03, 0x7b, 0xa7, 0xb9, 0x48, 0xe3, 0x7e, 0xb3, 0x6d, 0xc1, 0x06, 0x5a, 0x4e, 0xac,
	0x80, 0x36, 0x57, 0xa9, 0x80, 0xd6, 0x07, 0x4b, 0x5a, 0xf8, 0x02, 0xfc, 0x4a, 0xca, 0x38, 0x2c,
	0x1e, 0x68, 0xce, 0x67, 0x3c, 0xb8, 0x3e, 0xb0, 0x04, 0x2f, 0x1f, 0xbe, 0x7b, 0xb0, 0x63, 0x7a,
	0x9f, 0x47, 0xf3, 0x58, 0x1c, 0x43, 0xc9, 0x04, 0x0f, 0x99, 0xe0, 0x8f, 0xd5, 0x36, 0x0f, 0xcb,
	0x0f, 0x41, 0x74, 0xcb, 0xfe, 0x3c, 0xfd, 0x11, 0x00, 0x00, 0xff, 0xff, 0x57, 0xa3, 0xc2, 0x4f,
	0x1c, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SFUClient is the client API for SFU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SFUClient interface {
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (SFU_PublishClient, error)
	Unpublish(ctx context.Context, in *UnpublishRequest, opts ...grpc.CallOption) (*UnpublishReply, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error)
}

type sFUClient struct {
	cc *grpc.ClientConn
}

func NewSFUClient(cc *grpc.ClientConn) SFUClient {
	return &sFUClient{cc}
}

func (c *sFUClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (SFU_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SFU_serviceDesc.Streams[0], "/sfu.SFU/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &sFUPublishClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type SFU_PublishClient interface {
	Recv() (*PublishReply, error)
	grpc.ClientStream
}

type sFUPublishClient struct {
	grpc.ClientStream
}

func (x *sFUPublishClient) Recv() (*PublishReply, error) {
	m := new(PublishReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sFUClient) Unpublish(ctx context.Context, in *UnpublishRequest, opts ...grpc.CallOption) (*UnpublishReply, error) {
	out := new(UnpublishReply)
	err := c.cc.Invoke(ctx, "/sfu.SFU/Unpublish", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error) {
	out := new(SubscribeReply)
	err := c.cc.Invoke(ctx, "/sfu.SFU/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error) {
	out := new(UnsubscribeReply)
	err := c.cc.Invoke(ctx, "/sfu.SFU/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SFUServer is the server API for SFU service.
type SFUServer interface {
	Publish(*PublishRequest, SFU_PublishServer) error
	Unpublish(context.Context, *UnpublishRequest) (*UnpublishReply, error)
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error)
}

// UnimplementedSFUServer can be embedded to have forward compatible implementations.
type UnimplementedSFUServer struct {
}

func (*UnimplementedSFUServer) Publish(req *PublishRequest, srv SFU_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedSFUServer) Unpublish(ctx context.Context, req *UnpublishRequest) (*UnpublishReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unpublish not implemented")
}
func (*UnimplementedSFUServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedSFUServer) Unsubscribe(ctx context.Context, req *UnsubscribeRequest) (*UnsubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterSFUServer(s *grpc.Server, srv SFUServer) {
	s.RegisterService(&_SFU_serviceDesc, srv)
}

func _SFU_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(PublishRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SFUServer).Publish(m, &sFUPublishServer{stream})
}

type SFU_PublishServer interface {
	Send(*PublishReply) error
	grpc.ServerStream
}

type sFUPublishServer struct {
	grpc.ServerStream
}

func (x *sFUPublishServer) Send(m *PublishReply) error {
	return x.ServerStream.SendMsg(m)
}

func _SFU_Unpublish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnpublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServer).Unpublish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sfu.SFU/Unpublish",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServer).Unpublish(ctx, req.(*UnpublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFU_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sfu.SFU/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFU_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sfu.SFU/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SFU_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sfu.SFU",
	HandlerType: (*SFUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Unpublish",
			Handler:    _SFU_Unpublish_Handler,
		},
		{
			MethodName: "Subscribe",
			Handler:    _SFU_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _SFU_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _SFU_Publish_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pkg/proto/sfu.proto",
}
