// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/proto/sfu.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PublishRequest struct {
	Rid string `protobuf:"bytes,1,opt,name=rid,proto3" json:"rid,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*PublishRequest_Connect
	//	*PublishRequest_Trickle
	Payload              isPublishRequest_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *PublishRequest) Reset()         { *m = PublishRequest{} }
func (m *PublishRequest) String() string { return proto.CompactTextString(m) }
func (*PublishRequest) ProtoMessage()    {}
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{0}
}

func (m *PublishRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishRequest.Unmarshal(m, b)
}
func (m *PublishRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishRequest.Marshal(b, m, deterministic)
}
func (m *PublishRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishRequest.Merge(m, src)
}
func (m *PublishRequest) XXX_Size() int {
	return xxx_messageInfo_PublishRequest.Size(m)
}
func (m *PublishRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublishRequest proto.InternalMessageInfo

func (m *PublishRequest) GetRid() string {
	if m != nil {
		return m.Rid
	}
	return ""
}

type isPublishRequest_Payload interface {
	isPublishRequest_Payload()
}

type PublishRequest_Connect struct {
	Connect *Connect `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type PublishRequest_Trickle struct {
	Trickle *Trickle `protobuf:"bytes,3,opt,name=trickle,proto3,oneof"`
}

func (*PublishRequest_Connect) isPublishRequest_Payload() {}

func (*PublishRequest_Trickle) isPublishRequest_Payload() {}

func (m *PublishRequest) GetPayload() isPublishRequest_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PublishRequest) GetConnect() *Connect {
	if x, ok := m.GetPayload().(*PublishRequest_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *PublishRequest) GetTrickle() *Trickle {
	if x, ok := m.GetPayload().(*PublishRequest_Trickle); ok {
		return x.Trickle
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PublishRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PublishRequest_Connect)(nil),
		(*PublishRequest_Trickle)(nil),
	}
}

type PublishReply struct {
	Mid string `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	// Types that are valid to be assigned to Payload:
	//	*PublishReply_Connect
	//	*PublishReply_Trickle
	Payload              isPublishReply_Payload `protobuf_oneof:"payload"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PublishReply) Reset()         { *m = PublishReply{} }
func (m *PublishReply) String() string { return proto.CompactTextString(m) }
func (*PublishReply) ProtoMessage()    {}
func (*PublishReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{1}
}

func (m *PublishReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublishReply.Unmarshal(m, b)
}
func (m *PublishReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublishReply.Marshal(b, m, deterministic)
}
func (m *PublishReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublishReply.Merge(m, src)
}
func (m *PublishReply) XXX_Size() int {
	return xxx_messageInfo_PublishReply.Size(m)
}
func (m *PublishReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PublishReply.DiscardUnknown(m)
}

var xxx_messageInfo_PublishReply proto.InternalMessageInfo

func (m *PublishReply) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type isPublishReply_Payload interface {
	isPublishReply_Payload()
}

type PublishReply_Connect struct {
	Connect *Connect `protobuf:"bytes,2,opt,name=connect,proto3,oneof"`
}

type PublishReply_Trickle struct {
	Trickle *Trickle `protobuf:"bytes,3,opt,name=trickle,proto3,oneof"`
}

func (*PublishReply_Connect) isPublishReply_Payload() {}

func (*PublishReply_Trickle) isPublishReply_Payload() {}

func (m *PublishReply) GetPayload() isPublishReply_Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *PublishReply) GetConnect() *Connect {
	if x, ok := m.GetPayload().(*PublishReply_Connect); ok {
		return x.Connect
	}
	return nil
}

func (m *PublishReply) GetTrickle() *Trickle {
	if x, ok := m.GetPayload().(*PublishReply_Trickle); ok {
		return x.Trickle
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*PublishReply) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*PublishReply_Connect)(nil),
		(*PublishReply_Trickle)(nil),
	}
}

type SubscribeRequest struct {
	Mid                  string              `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Options              *Options            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubscribeRequest) Reset()         { *m = SubscribeRequest{} }
func (m *SubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*SubscribeRequest) ProtoMessage()    {}
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{2}
}

func (m *SubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeRequest.Unmarshal(m, b)
}
func (m *SubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeRequest.Marshal(b, m, deterministic)
}
func (m *SubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeRequest.Merge(m, src)
}
func (m *SubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_SubscribeRequest.Size(m)
}
func (m *SubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeRequest proto.InternalMessageInfo

func (m *SubscribeRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *SubscribeRequest) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

func (m *SubscribeRequest) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type SubscribeReply struct {
	Mid                  string              `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	Description          *SessionDescription `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *SubscribeReply) Reset()         { *m = SubscribeReply{} }
func (m *SubscribeReply) String() string { return proto.CompactTextString(m) }
func (*SubscribeReply) ProtoMessage()    {}
func (*SubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{3}
}

func (m *SubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SubscribeReply.Unmarshal(m, b)
}
func (m *SubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SubscribeReply.Marshal(b, m, deterministic)
}
func (m *SubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SubscribeReply.Merge(m, src)
}
func (m *SubscribeReply) XXX_Size() int {
	return xxx_messageInfo_SubscribeReply.Size(m)
}
func (m *SubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_SubscribeReply proto.InternalMessageInfo

func (m *SubscribeReply) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

func (m *SubscribeReply) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

type UnsubscribeRequest struct {
	Mid                  string   `protobuf:"bytes,1,opt,name=mid,proto3" json:"mid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeRequest) Reset()         { *m = UnsubscribeRequest{} }
func (m *UnsubscribeRequest) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeRequest) ProtoMessage()    {}
func (*UnsubscribeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{4}
}

func (m *UnsubscribeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeRequest.Unmarshal(m, b)
}
func (m *UnsubscribeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeRequest.Marshal(b, m, deterministic)
}
func (m *UnsubscribeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeRequest.Merge(m, src)
}
func (m *UnsubscribeRequest) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeRequest.Size(m)
}
func (m *UnsubscribeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeRequest proto.InternalMessageInfo

func (m *UnsubscribeRequest) GetMid() string {
	if m != nil {
		return m.Mid
	}
	return ""
}

type UnsubscribeReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UnsubscribeReply) Reset()         { *m = UnsubscribeReply{} }
func (m *UnsubscribeReply) String() string { return proto.CompactTextString(m) }
func (*UnsubscribeReply) ProtoMessage()    {}
func (*UnsubscribeReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{5}
}

func (m *UnsubscribeReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UnsubscribeReply.Unmarshal(m, b)
}
func (m *UnsubscribeReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UnsubscribeReply.Marshal(b, m, deterministic)
}
func (m *UnsubscribeReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UnsubscribeReply.Merge(m, src)
}
func (m *UnsubscribeReply) XXX_Size() int {
	return xxx_messageInfo_UnsubscribeReply.Size(m)
}
func (m *UnsubscribeReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UnsubscribeReply.DiscardUnknown(m)
}

var xxx_messageInfo_UnsubscribeReply proto.InternalMessageInfo

type SessionDescription struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Sdp                  string   `protobuf:"bytes,2,opt,name=sdp,proto3" json:"sdp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SessionDescription) Reset()         { *m = SessionDescription{} }
func (m *SessionDescription) String() string { return proto.CompactTextString(m) }
func (*SessionDescription) ProtoMessage()    {}
func (*SessionDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{6}
}

func (m *SessionDescription) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SessionDescription.Unmarshal(m, b)
}
func (m *SessionDescription) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SessionDescription.Marshal(b, m, deterministic)
}
func (m *SessionDescription) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SessionDescription.Merge(m, src)
}
func (m *SessionDescription) XXX_Size() int {
	return xxx_messageInfo_SessionDescription.Size(m)
}
func (m *SessionDescription) XXX_DiscardUnknown() {
	xxx_messageInfo_SessionDescription.DiscardUnknown(m)
}

var xxx_messageInfo_SessionDescription proto.InternalMessageInfo

func (m *SessionDescription) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *SessionDescription) GetSdp() string {
	if m != nil {
		return m.Sdp
	}
	return ""
}

type Connect struct {
	Description          *SessionDescription `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Options              *Options            `protobuf:"bytes,2,opt,name=options,proto3" json:"options,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Connect) Reset()         { *m = Connect{} }
func (m *Connect) String() string { return proto.CompactTextString(m) }
func (*Connect) ProtoMessage()    {}
func (*Connect) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{7}
}

func (m *Connect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Connect.Unmarshal(m, b)
}
func (m *Connect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Connect.Marshal(b, m, deterministic)
}
func (m *Connect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Connect.Merge(m, src)
}
func (m *Connect) XXX_Size() int {
	return xxx_messageInfo_Connect.Size(m)
}
func (m *Connect) XXX_DiscardUnknown() {
	xxx_messageInfo_Connect.DiscardUnknown(m)
}

var xxx_messageInfo_Connect proto.InternalMessageInfo

func (m *Connect) GetDescription() *SessionDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *Connect) GetOptions() *Options {
	if m != nil {
		return m.Options
	}
	return nil
}

type Trickle struct {
	Candidate            string   `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Trickle) Reset()         { *m = Trickle{} }
func (m *Trickle) String() string { return proto.CompactTextString(m) }
func (*Trickle) ProtoMessage()    {}
func (*Trickle) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{8}
}

func (m *Trickle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Trickle.Unmarshal(m, b)
}
func (m *Trickle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Trickle.Marshal(b, m, deterministic)
}
func (m *Trickle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Trickle.Merge(m, src)
}
func (m *Trickle) XXX_Size() int {
	return xxx_messageInfo_Trickle.Size(m)
}
func (m *Trickle) XXX_DiscardUnknown() {
	xxx_messageInfo_Trickle.DiscardUnknown(m)
}

var xxx_messageInfo_Trickle proto.InternalMessageInfo

func (m *Trickle) GetCandidate() string {
	if m != nil {
		return m.Candidate
	}
	return ""
}

type Options struct {
	Bandwidth            uint32   `protobuf:"varint,1,opt,name=bandwidth,proto3" json:"bandwidth,omitempty"`
	Transportcc          bool     `protobuf:"varint,2,opt,name=transportcc,proto3" json:"transportcc,omitempty"`
	Codec                string   `protobuf:"bytes,3,opt,name=codec,proto3" json:"codec,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Options) Reset()         { *m = Options{} }
func (m *Options) String() string { return proto.CompactTextString(m) }
func (*Options) ProtoMessage()    {}
func (*Options) Descriptor() ([]byte, []int) {
	return fileDescriptor_e599a6ad2e115568, []int{9}
}

func (m *Options) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Options.Unmarshal(m, b)
}
func (m *Options) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Options.Marshal(b, m, deterministic)
}
func (m *Options) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Options.Merge(m, src)
}
func (m *Options) XXX_Size() int {
	return xxx_messageInfo_Options.Size(m)
}
func (m *Options) XXX_DiscardUnknown() {
	xxx_messageInfo_Options.DiscardUnknown(m)
}

var xxx_messageInfo_Options proto.InternalMessageInfo

func (m *Options) GetBandwidth() uint32 {
	if m != nil {
		return m.Bandwidth
	}
	return 0
}

func (m *Options) GetTransportcc() bool {
	if m != nil {
		return m.Transportcc
	}
	return false
}

func (m *Options) GetCodec() string {
	if m != nil {
		return m.Codec
	}
	return ""
}

func init() {
	proto.RegisterType((*PublishRequest)(nil), "sfu.PublishRequest")
	proto.RegisterType((*PublishReply)(nil), "sfu.PublishReply")
	proto.RegisterType((*SubscribeRequest)(nil), "sfu.SubscribeRequest")
	proto.RegisterType((*SubscribeReply)(nil), "sfu.SubscribeReply")
	proto.RegisterType((*UnsubscribeRequest)(nil), "sfu.UnsubscribeRequest")
	proto.RegisterType((*UnsubscribeReply)(nil), "sfu.UnsubscribeReply")
	proto.RegisterType((*SessionDescription)(nil), "sfu.SessionDescription")
	proto.RegisterType((*Connect)(nil), "sfu.Connect")
	proto.RegisterType((*Trickle)(nil), "sfu.Trickle")
	proto.RegisterType((*Options)(nil), "sfu.Options")
}

func init() { proto.RegisterFile("pkg/proto/sfu.proto", fileDescriptor_e599a6ad2e115568) }

var fileDescriptor_e599a6ad2e115568 = []byte{
	// 463 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x94, 0xc1, 0x6f, 0xd3, 0x30,
	0x14, 0xc6, 0x97, 0x15, 0x08, 0x79, 0x1d, 0x53, 0x79, 0x65, 0xa2, 0xaa, 0x38, 0x94, 0x20, 0x8d,
	0x5e, 0x68, 0xd0, 0x38, 0xa0, 0x71, 0x41, 0x1a, 0x08, 0x71, 0x03, 0xb9, 0xec, 0x82, 0x84, 0x50,
	0x62, 0xbb, 0xab, 0xb5, 0xd4, 0x36, 0xb1, 0x23, 0xd4, 0x13, 0xe2, 0xc4, 0xff, 0xc4, 0x5f, 0x87,
	0xec, 0xa4, 0x6d, 0x9a, 0x22, 0x51, 0x0e, 0x3b, 0xf5, 0xe5, 0x7b, 0x9f, 0xbf, 0xfe, 0xfa, 0x9e,
	0x1b, 0xe8, 0xeb, 0xeb, 0xab, 0x44, 0x17, 0xca, 0xaa, 0xc4, 0xcc, 0xca, 0x89, 0xaf, 0xb0, 0x63,
	0x66, 0x65, 0xfc, 0x33, 0x80, 0xe3, 0x8f, 0x65, 0x96, 0x0b, 0x33, 0x27, 0xfc, 0x5b, 0xc9, 0x8d,
	0xc5, 0x1e, 0x74, 0x0a, 0xc1, 0x06, 0xc1, 0x28, 0x18, 0x47, 0xc4, 0x95, 0x38, 0x86, 0x90, 0x2a,
	0x29, 0x39, 0xb5, 0x83, 0xc3, 0x51, 0x30, 0xee, 0x9e, 0x1d, 0x4d, 0x5c, 0xcc, 0x9b, 0x4a, 0x7b,
	0x7f, 0x40, 0x56, 0x6d, 0xe7, 0xb4, 0x85, 0xa0, 0xd7, 0x39, 0x1f, 0x74, 0x1a, 0xce, 0x4f, 0x95,
	0xe6, 0x9c, 0x75, 0xfb, 0x22, 0x82, 0x50, 0xa7, 0xcb, 0x5c, 0xa5, 0x2c, 0xfe, 0x01, 0x47, 0x6b,
	0x04, 0x9d, 0x2f, 0x1d, 0xc0, 0x62, 0x03, 0xb0, 0xb8, 0x79, 0x80, 0x5f, 0x01, 0xf4, 0xa6, 0x65,
	0x66, 0x68, 0x21, 0x32, 0xde, 0x18, 0x43, 0x8b, 0xe2, 0x14, 0x42, 0xa5, 0xad, 0x50, 0xd2, 0x6c,
	0x51, 0x7c, 0xa8, 0x34, 0xb2, 0x6a, 0xe2, 0x39, 0x74, 0x19, 0x77, 0x61, 0xfe, 0xb9, 0xe6, 0x78,
	0xe8, 0xbd, 0x53, 0x6e, 0x8c, 0x50, 0xf2, 0xed, 0xa6, 0x4d, 0x9a, 0xde, 0xf8, 0x0b, 0x1c, 0x37,
	0x40, 0xfe, 0x3e, 0x8c, 0x56, 0xfc, 0xe1, 0x7f, 0xc4, 0x9f, 0x02, 0x5e, 0x4a, 0xf3, 0xcf, 0x5f,
	0x1a, 0x23, 0xf4, 0xb6, 0x7c, 0x3a, 0x5f, 0xc6, 0xaf, 0x00, 0x77, 0xe3, 0x11, 0xe1, 0x96, 0x5d,
	0x6a, 0x5e, 0x1f, 0xf6, 0xb5, 0xcb, 0x33, 0x4c, 0x7b, 0xb0, 0x88, 0xb8, 0x32, 0xce, 0x21, 0xac,
	0x77, 0xd5, 0xa6, 0x0f, 0xf6, 0xa7, 0xdf, 0x77, 0xfe, 0xf1, 0x53, 0x08, 0xeb, 0x7d, 0xe3, 0x23,
	0x88, 0x68, 0x2a, 0x99, 0x60, 0xa9, 0x5d, 0x31, 0x6e, 0x84, 0xf8, 0x2b, 0x84, 0xf5, 0x61, 0x67,
	0xcc, 0x52, 0xc9, 0xbe, 0x0b, 0x66, 0xe7, 0xde, 0x78, 0x8f, 0x6c, 0x04, 0x1c, 0x41, 0xd7, 0x16,
	0xa9, 0x34, 0x5a, 0x15, 0x96, 0x52, 0xff, 0xed, 0x77, 0x49, 0x53, 0xc2, 0x07, 0x70, 0x9b, 0x2a,
	0xc6, 0xa9, 0xdf, 0x76, 0x44, 0xaa, 0x87, 0xb3, 0xdf, 0x01, 0x74, 0xa6, 0xef, 0x2e, 0xf1, 0x25,
	0x84, 0xf5, 0x0d, 0xc7, 0xbe, 0x67, 0xde, 0xfe, 0xcb, 0x0d, 0xef, 0x6f, 0x8b, 0x6e, 0xdc, 0x07,
	0xe3, 0xe0, 0x79, 0x80, 0xe7, 0x10, 0xad, 0xef, 0x03, 0x9e, 0x54, 0x53, 0x6a, 0xad, 0x6f, 0xd8,
	0x6f, 0xcb, 0xfe, 0x38, 0xbe, 0x86, 0x6e, 0x63, 0x87, 0x58, 0x8d, 0x78, 0x77, 0xfb, 0xc3, 0x93,
	0xdd, 0x86, 0x0f, 0xb8, 0x78, 0xf2, 0xf9, 0xf1, 0x95, 0xb0, 0xf3, 0x32, 0x9b, 0x50, 0xb5, 0x48,
	0xb4, 0x50, 0x32, 0x11, 0x4a, 0x3e, 0x33, 0xb3, 0x32, 0x59, 0xbf, 0x4e, 0xb2, 0x3b, 0xfe, 0xe3,
	0xc5, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x02, 0x6a, 0x7f, 0x62, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SFUClient is the client API for SFU service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SFUClient interface {
	Publish(ctx context.Context, opts ...grpc.CallOption) (SFU_PublishClient, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error)
}

type sFUClient struct {
	cc *grpc.ClientConn
}

func NewSFUClient(cc *grpc.ClientConn) SFUClient {
	return &sFUClient{cc}
}

func (c *sFUClient) Publish(ctx context.Context, opts ...grpc.CallOption) (SFU_PublishClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SFU_serviceDesc.Streams[0], "/sfu.SFU/Publish", opts...)
	if err != nil {
		return nil, err
	}
	x := &sFUPublishClient{stream}
	return x, nil
}

type SFU_PublishClient interface {
	Send(*PublishRequest) error
	Recv() (*PublishReply, error)
	grpc.ClientStream
}

type sFUPublishClient struct {
	grpc.ClientStream
}

func (x *sFUPublishClient) Send(m *PublishRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sFUPublishClient) Recv() (*PublishReply, error) {
	m := new(PublishReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *sFUClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (*SubscribeReply, error) {
	out := new(SubscribeReply)
	err := c.cc.Invoke(ctx, "/sfu.SFU/Subscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sFUClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeReply, error) {
	out := new(UnsubscribeReply)
	err := c.cc.Invoke(ctx, "/sfu.SFU/Unsubscribe", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SFUServer is the server API for SFU service.
type SFUServer interface {
	Publish(SFU_PublishServer) error
	Subscribe(context.Context, *SubscribeRequest) (*SubscribeReply, error)
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeReply, error)
}

// UnimplementedSFUServer can be embedded to have forward compatible implementations.
type UnimplementedSFUServer struct {
}

func (*UnimplementedSFUServer) Publish(srv SFU_PublishServer) error {
	return status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (*UnimplementedSFUServer) Subscribe(ctx context.Context, req *SubscribeRequest) (*SubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (*UnimplementedSFUServer) Unsubscribe(ctx context.Context, req *UnsubscribeRequest) (*UnsubscribeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}

func RegisterSFUServer(s *grpc.Server, srv SFUServer) {
	s.RegisterService(&_SFU_serviceDesc, srv)
}

func _SFU_Publish_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SFUServer).Publish(&sFUPublishServer{stream})
}

type SFU_PublishServer interface {
	Send(*PublishReply) error
	Recv() (*PublishRequest, error)
	grpc.ServerStream
}

type sFUPublishServer struct {
	grpc.ServerStream
}

func (x *sFUPublishServer) Send(m *PublishReply) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sFUPublishServer) Recv() (*PublishRequest, error) {
	m := new(PublishRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _SFU_Subscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServer).Subscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sfu.SFU/Subscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServer).Subscribe(ctx, req.(*SubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SFU_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SFUServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sfu.SFU/Unsubscribe",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SFUServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SFU_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sfu.SFU",
	HandlerType: (*SFUServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Subscribe",
			Handler:    _SFU_Subscribe_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _SFU_Unsubscribe_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Publish",
			Handler:       _SFU_Publish_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/proto/sfu.proto",
}
