name: build grpc
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build grpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build grpc
        run: make build_grpc
        
