name: build json-rpc
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build json-rpc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: build json-rpc
        run: make build_jsonrpc
