name: development docker
on:
  push:
    branches:
    - master
    release:
      types: [created]
  pull_request:
    branches:
    - master
jobs:
  build:
    name: build and push
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
    
      - name: build
        run: docker build --tag pionwebrtc/ion-sfu:latest-devel .

      - name: login
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: tag
        if: github.event_name == 'push'
        run: docker tag pionwebrtc/ion-sfu:latest-devel

      - name: push
        if: github.event_name == 'push'
        run: docker push pionwebrtc/ion-sfu:latest-devel
