name: docker
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
jobs:
  build:
    name: protoc
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v2
    
      - name: build
        run: docker build --tag pionwebrtc/ion-sfu:latest-protoc -f cmd/signal/grpc/proto/Dockerfile .

      - name: login
        if: github.event_name == 'push'
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: push
        if: github.event_name == 'push'
        run: docker push pionwebrtc/ion-sfu:latest-protoc
