name: lint all
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt update && sudo apt install libc-dev libvpx-dev v4l-utils

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          version: v1.29
